### ISSUE TITLE
Unable to start activity

### ISSUE THREAD

**Issue by kuyoonjo** [PingPlusPlus/pingpp-android#35]
错误信息如下：

```
09-11 02:19:43.020 30603-30603/news.chen.yu.ionic E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: news.chen.yu.ionic, PID: 30603
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{news.chen.yu.ionic/com.pingplusplus.android.PaymentActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                        at android.app.ActivityThread.access$900(ActivityThread.java:172)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:145)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5835)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                        at android.content.res.Resources.getValue(Resources.java:2333)
                                                                        at android.content.res.Resources.loadXmlResourceParser(Resources.java:3881)
                                                                        at android.content.res.Resources.getLayout(Resources.java:2149)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
                                                                        at com.pingplusplus.android.p.<init>(Unknown Source)
                                                                        at com.pingplusplus.android.PaymentActivity.b(Unknown Source)
                                                                        at com.pingplusplus.android.PaymentActivity.onCreate(Unknown Source)
                                                                        at android.app.Activity.performCreate(Activity.java:6221)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                        at android.app.ActivityThread.access$900(ActivityThread.java:172) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:145) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5835) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
```

**Comment by dong11** [comment]
资源文件拷贝到你的项目中了吗？

**Comment by kuyoonjo** [comment]
res, assets 拷贝完问题解决。
不过高德地图用不了了。是有冲突吗？
E/AndroidRuntime(18983): java.lang.UnsatisfiedLinkError: No implementation found for long com.autonavi.amap.mapcore.MapCore.nativeNewInstance(java.lang.String, java.lang.String) (tried Java_com_autonavi_amap_mapcore_MapCore_nativeNewInstance and Java_com_autonavi_amap_mapcore_MapCore_nativeNewInstance__Ljava_lang_String_2Ljava_lang_String_2)
E/AndroidRuntime(18983): 	at com.autonavi.amap.mapcore.MapCore.nativeNewInstance(Native Method)
E/AndroidRuntime(18983): 	at com.autonavi.amap.mapcore.MapCore.newMap(MapCore.java:83)
E/AndroidRuntime(18983): 	at com.amap.api.mapcore.util.c.m(AMapDelegateImp.java:590)
E/AndroidRuntime(18983): 	at com.amap.api.mapcore.util.c.<init>(AMapDelegateImp.java:322)
E/AndroidRuntime(18983): 	at com.amap.api.mapcore.util.c.<init>(AMapDelegateImp.java:301)
E/AndroidRuntime(18983): 	at com.amap.api.mapcore.util.k.<init>(AMapGLSurfaceView.java:27)
E/AndroidRuntime(18983): 	at com.amap.api.mapcore.util.k.<init>(AMapGLSurfaceView.java:21)
E/AndroidRuntime(18983): 	at com.amap.api.mapcore.util.ab.onCreateView(MapFragmentDelegateImp.java:133)
E/AndroidRuntime(18983): 	at com.amap.api.maps.SupportMapFragment.onCreateView(SupportMapFragment.java:135)
E/AndroidRuntime(18983): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
E/AndroidRuntime(18983): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
E/AndroidRuntime(18983): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
E/AndroidRuntime(18983): 	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
E/AndroidRuntime(18983): 	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
E/AndroidRuntime(18983): 	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
E/AndroidRuntime(18983): 	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
E/AndroidRuntime(18983): 	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
E/AndroidRuntime(18983): 	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
E/AndroidRuntime(18983): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:740)
E/AndroidRuntime(18983): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
E/AndroidRuntime(18983): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
E/AndroidRuntime(18983): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
E/AndroidRuntime(18983): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
E/AndroidRuntime(18983): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:428)
E/AndroidRuntime(18983): 	at android.app.Activity.setContentView(Activity.java:2241)
E/AndroidRuntime(18983): 	at news.chen.yu.ionic.YCAmapActivity.onCreate(YCAmapActivity.java:24)
E/AndroidRuntime(18983): 	at android.app.Activity.performCreate(Activity.java:6221)
E/AndroidRuntime(18983): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime(18983): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
E/AndroidRuntime(18983): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
E/AndroidRuntime(18983): 	at android.app.ActivityThread.access$900(ActivityThread.java:172)
E/AndroidRuntime(18983): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
E/AndroidRuntime(18983): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18983): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(18983): 	at android.app.ActivityThread.main(ActivityThread.java:5835)
E/AndroidRuntime(18983): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18983): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(18983): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(18983): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by kuyoonjo** [comment]
http://www.weyye.me/detail/sdk-so/ 已解决。
^^ 谢谢。
