### ISSUE TITLE
Gradle升级到3.3 android studio用2.3 example 报错了

### ISSUE THREAD

**Issue by gakaki** [PingPlusPlus/pingpp-android#43]
Executing tasks: [:example:assembleDebug]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:example:preBuild UP-TO-DATE
:example:preDebugBuild UP-TO-DATE
:example:checkDebugManifest
:lib:bdwallet_pay_sdk:preBuild UP-TO-DATE
:lib:bdwallet_pay_sdk:preReleaseBuild UP-TO-DATE
:lib:bdwallet_pay_sdk:checkReleaseManifest
:lib:bdwallet_pay_sdk:prepareReleaseDependencies
:lib:bdwallet_pay_sdk:compileReleaseAidl UP-TO-DATE
:lib:bdwallet_pay_sdk:compileReleaseNdk UP-TO-DATE
:lib:bdwallet_pay_sdk:compileLint UP-TO-DATE
:lib:bdwallet_pay_sdk:copyReleaseLint UP-TO-DATE
:lib:bdwallet_pay_sdk:mergeReleaseShaders UP-TO-DATE
:lib:bdwallet_pay_sdk:compileReleaseShaders UP-TO-DATE
:lib:bdwallet_pay_sdk:generateReleaseAssets UP-TO-DATE
:lib:bdwallet_pay_sdk:mergeReleaseAssets UP-TO-DATE
:lib:bdwallet_pay_sdk:mergeReleaseProguardFiles UP-TO-DATE
:lib:bdwallet_pay_sdk:packageReleaseRenderscript UP-TO-DATE
:lib:bdwallet_pay_sdk:compileReleaseRenderscript UP-TO-DATE
:lib:bdwallet_pay_sdk:generateReleaseResValues UP-TO-DATE
:lib:bdwallet_pay_sdk:generateReleaseResources UP-TO-DATE
:lib:bdwallet_pay_sdk:packageReleaseResources UP-TO-DATE
:lib:bdwallet_pay_sdk:processReleaseManifest UP-TO-DATE
:lib:bdwallet_pay_sdk:generateReleaseBuildConfig UP-TO-DATE
:lib:bdwallet_pay_sdk:processReleaseResources
:lib:bdwallet_pay_sdk:generateReleaseSources
:lib:bdwallet_pay_sdk:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:lib:bdwallet_pay_sdk:javaPreCompileRelease
:lib:bdwallet_pay_sdk:compileReleaseJavaWithJavac UP-TO-DATE
:lib:bdwallet_pay_sdk:processReleaseJavaRes UP-TO-DATE
:lib:bdwallet_pay_sdk:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:lib:bdwallet_pay_sdk:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:lib:bdwallet_pay_sdk:mergeReleaseJniLibFolders UP-TO-DATE
:lib:bdwallet_pay_sdk:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:lib:bdwallet_pay_sdk:transformNativeLibsWithStripDebugSymbolForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:bdwallet_pay_sdk:transformNativeLibsWithStripDebugSymbolForRelease'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':lib:bdwallet_pay_sdk:transformNativeLibsWithStripDebugSymbolForRelease'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException
	at com.android.ide.common.process.ProcessInfoBuilder.setExecutable(ProcessInfoBuilder.java:97)
	at com.android.build.gradle.internal.transforms.StripDebugSymbolTransform.stripFile(StripDebugSymbolTransform.java:223)
	at com.android.build.gradle.internal.transforms.StripDebugSymbolTransform.transform(StripDebugSymbolTransform.java:187)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 78 more

BUILD FAILED

Total time: 1.125 secs

**Comment by dong11** [comment]
@gakaki 升级ndk 或者禁用ndk 试试

**Comment by jiantao88** [comment]
我也碰到这个问题了，如何解决的？

**Comment by jiantao88** [comment]
![image](https://cloud.githubusercontent.com/assets/7411102/24093571/79e29bb4-0d8f-11e7-82a0-8186d3e6e3f8.png)

**Comment by dong11** [comment]
@jiantao88 升级一下ndk  或者禁用ndk 或者 将libpingpp中build.gradle中的ndk部分注释掉

**Comment by dong11** [comment]
@jiantao88 那你禁用ndk试试

**Comment by jiantao88** [comment]
![image](https://cloud.githubusercontent.com/assets/7411102/24095233/1d9d123c-0d97-11e7-9ef6-a05cd6e618e3.png)
取消这个么？还是没有解决

**Comment by dong11** [comment]
@jiantao88 不是  有一个local.properties文件来配置本地的开发环境的路径的  你只需要将ndk的路径注释掉就行

**Comment by sunkeding** [comment]
按照上面的说法做了，还是出现问题

**Comment by SnailMyth** [comment]
有解决这个问题的了吗？

**Comment by dong11** [comment]
@SnailMyth @sunkeding classpath 'com.android.tools.build:gradle:2.1.0'这边写的是哪个版本？

**Comment by dong11** [comment]
以上gradle更新到3.3 Android Studio更新到2.3的   将compileSdkVersion提高到23及以上即可 可能在gradle3.3下不支持compileSdkVersion为23以下进行NDK编译

**Comment by provswin** [comment]
我这里compileSdkVersion25，还是会有这个问题

**Comment by dong11** [comment]
@provswin gradle的版本是什么？

**Comment by provswin** [comment]
@dong11 刚可以了，是因为我前两天安装了NDK，把NDK卸载了就可以了，谢谢。
不过安装的是最新的NDK，还是不行。
也尝试过将local.properties中的ndk.dir注释掉，也是不行。

**Comment by xiaviv** [comment]
解决没？

**Comment by wangyg1990** [comment]
@dong11 fixed mine.

**Comment by wangdongyi** [comment]
我的也是，移除了jni 然后在删掉ndk 项目才能运行

**Comment by shiyuetyz** [comment]
在Android studio中卸载掉ndk，重新编译后就可以了。

**Comment by niu2x** [comment]
是由于工程里 提供了某种 abi的 so 文件，而gradle 不能处理这种abi。  可能是 gradle版本 太新或者 太低导致的。  可以查gradle的版本更新记录，看看对abi支持的变化。 在工程里删掉那些 不再支持的abi so文件，
