### ISSUE TITLE
Ionic APP 在安卓中使用支付功能会出现闪退问题，日志报错信息（请导入activity_pingpp_payment.xml文件）

### ISSUE THREAD

**Issue by realmx** [PingPlusPlus/pingpp-android#53]
Android版本4.x，5.x，6.x，7.x都试过，均闪退，iOS没问题
android sdk：最新版本2.1.9
me.tongchia.cordova.pingpp：最新版本1.0.1
plugin.xml做了修改，否则无法安装，提示找不到文件
```xml
<!--android要修改两个文件链接，不然platform android无法安装，不知道是不是这个原因引起的-->
<source-file src="sdk/android/lib/pingpp/libs/alipaySingle-20161222.jar" target-dir="libs"/>
<source-file src="sdk/android/lib/pingpp/libs/libammsdk.jar" target-dir="libs"/>
<source-file src="sdk/android/lib/pingpp/libs/libpingpp-2.1.9.jar" target-dir="libs"/>
<!--屏蔽了Wx目录，不然platform ios无法安装-->
<!--<source-file src="sdk/ios/lib/Channels/Wx/libpingpp+wx.a" framework="true"/>
        <source-file src="sdk/ios/lib/Channels/Wx/libWeChatSDK.a" framework="true"/>
        <header-file src="sdk/ios/lib/Channels/Wx/WXApi.h" />
        <header-file src="sdk/ios/lib/Channels/Wx/WXApiObject.h" />-->
```
下面是Android Studio的Android Monitor / logcat日志信息，用的是Android Studio自带的emulator模拟器
```log
04-18 15:09:40.004 12961-12961/me.example.app E/PING++: 请导入activity_pingpp_payment.xml文件
                                                            
                                                            --------- beginning of crash
04-18 15:09:40.006 12961-13037/me.example.app E/AndroidRuntime: FATAL EXCEPTION: Thread-8
                                                                    Process: me.example.app, PID: 12961
                                                                    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.example.app-1/base.apk"],nativeLibraryDirectories=[/data/app/me.example.app-1/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libpingpp.so"
                                                                        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                                        at java.lang.System.loadLibrary(System.java:1530)
                                                                        at com.pingplusplus.android.crypto.Crypt.<clinit>(Unknown Source)
                                                                        at com.pingplusplus.android.crypto.CryptoUtils.encryptData(Unknown Source)
                                                                        at com.pingplusplus.android.Pingpp.encryptData(Unknown Source)
                                                                        at com.pingplusplus.android.k.b(Unknown Source)
                                                                        at com.pingplusplus.android.PingppDataCollection.<init>(Unknown Source)
                                                                        at com.pingplusplus.android.a.run(Unknown Source)
                                                                        at java.lang.Thread.run(Thread.java:761)
```

截图
![wechatimg1](https://cloud.githubusercontent.com/assets/6071313/25118670/d60e2fcc-2449-11e7-96ba-0f7c858738db.jpeg)

**Comment by realmx** [comment]
@dong11 求助

**Comment by dong11** [comment]
@realmx  使用官方的https://coding.net/u/pingplusplus/p/pingpp-cordova/git 试试

**Comment by realmx** [comment]
@dong11 非常感谢！Android/iOS都能顺利调起支付测试页面，并且能回调原APP
