### ISSUE TITLE
试用版换为广告版出错

### ISSUE THREAD

**Issue by androidzhoufeng** [PingPlusPlus/pingpp-android#62]
广告版调用方法PingppUI.createPay(.this, data, paymentHandler);时报错：
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dp0086.dqzb/com.pingplusplus.ui.PayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.pingplusplus.ui.ProgressWheel.setVisibility(int)' on a null object reference
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
	   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532)
	   at android.app.ActivityThread.access$800(ActivityThread.java:169)
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
	   at android.os.Handler.dispatchMessage(Handler.java:111)
	   at android.os.Looper.loop(Looper.java:194)
	   at android.app.ActivityThread.main(ActivityThread.java:5556)
	   at java.lang.reflect.Method.invoke(Native Method)
	   at java.lang.reflect.Method.invoke(Method.java:372)
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
	Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.pingplusplus.ui.ProgressWheel.setVisibility(int)' on a null object reference
	   at com.pingplusplus.ui.PayActivity$b.handleMessage(Unknown Source)
	   at com.pingplusplus.ui.PayActivity.onCreate(Unknown Source)
	   at android.app.Activity.performCreate(Activity.java:5975)
	   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
	   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532) 
	   at android.app.ActivityThread.access$800(ActivityThread.java:169) 
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
	   at android.os.Handler.dispatchMessage(Handler.java:111) 
	   at android.os.Looper.loop(Looper.java:194) 
	   at android.app.ActivityThread.main(ActivityThread.java:5556) 
	   at java.lang.reflect.Method.invoke(Native Method) 
	   at java.lang.reflect.Method.invoke(Method.java:372) 
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by androidzhoufeng** [comment]
与什么冲突会报这个错误？我在另外第一个项目中同样的写法是没有问题的。
